import { EditorView } from '@codemirror/view'
import { HighlightStyle } from '@codemirror/language'
import { tags } from '@lezer/highlight'

export const amberTheme = EditorView.theme({
  '&': {
    height: '100%',
    backgroundColor: '#0b0907',
    color: '#f0e6d8',
    fontSize: '13.5px',
    fontFamily: '"Geist Mono", "JetBrains Mono", ui-monospace, monospace',
  },
  '.cm-scroller': { overflow: 'auto', scrollbarWidth: 'thin', scrollbarColor: '#2e2520 transparent' },
  '.cm-content': { padding: '16px 0', caretColor: '#e8943a' },
  '.cm-cursor': { borderLeftColor: '#e8943a', borderLeftWidth: '2px' },
  '.cm-line': { padding: '0 18px' },
  '.cm-gutters': {
    backgroundColor: '#0b0907',
    borderRight: '1px solid #1c1714',
    color: '#56493e',
    paddingRight: '4px',
  },
  '.cm-gutter': { minWidth: '46px' },
  '.cm-lineNumbers .cm-gutterElement': { padding: '0 6px 0 8px' },
  '.cm-activeLineGutter': { backgroundColor: '#1a1512', color: '#9e8e7a' },
  '.cm-activeLine': { backgroundColor: 'rgba(26, 21, 18, 0.6)' },
  '.cm-selectionBackground': { backgroundColor: 'rgba(232, 148, 58, 0.18) !important' },
  '&.cm-focused': { outline: 'none' },
  '&.cm-focused .cm-selectionBackground': { backgroundColor: 'rgba(232, 148, 58, 0.22) !important' },
  '.cm-matchingBracket': {
    backgroundColor: 'rgba(232, 148, 58, 0.25)',
    outline: '1px solid rgba(232, 148, 58, 0.45)',
    borderRadius: '1px',
  },
  '.cm-nonmatchingBracket': { backgroundColor: 'rgba(224, 80, 64, 0.25)' },
  '.cm-foldGutter .cm-gutterElement': { color: '#56493e', cursor: 'pointer' },
  '.cm-foldGutter .cm-gutterElement:hover': { color: '#e8943a' },
  '.cm-tooltip': {
    backgroundColor: '#1a1512',
    border: '1px solid #2e2520',
    borderRadius: '2px',
  },
  '.cm-searchMatch': { backgroundColor: 'rgba(232, 148, 58, 0.25)', outline: '1px solid rgba(232, 148, 58, 0.4)' },
  '.cm-searchMatch.cm-searchMatch-selected': { backgroundColor: 'rgba(232, 148, 58, 0.4)' },
  '.cm-selectionMatch': { backgroundColor: 'rgba(232, 148, 58, 0.12)' },
}, { dark: true })

export const amberHighlight = HighlightStyle.define([
  { tag: tags.keyword,           color: '#e8943a', fontWeight: '500' },
  { tag: tags.controlKeyword,    color: '#e8943a' },
  { tag: tags.operatorKeyword,   color: '#e8943a' },
  { tag: tags.definitionKeyword, color: '#e8943a' },
  { tag: tags.moduleKeyword,     color: '#e8943a' },
  { tag: tags.string,            color: '#6ab08a' },
  { tag: tags.special(tags.string), color: '#5aad8a' },
  { tag: tags.number,            color: '#89b8d4' },
  { tag: tags.integer,           color: '#89b8d4' },
  { tag: tags.float,             color: '#89b8d4' },
  { tag: tags.bool,              color: '#c87060' },
  { tag: tags.null,              color: '#c87060' },
  { tag: tags.comment,           color: '#4a3e34', fontStyle: 'italic' },
  { tag: tags.lineComment,       color: '#4a3e34', fontStyle: 'italic' },
  { tag: tags.blockComment,      color: '#4a3e34', fontStyle: 'italic' },
  { tag: tags.name,              color: '#f0e6d8' },
  { tag: tags.variableName,      color: '#f0e6d8' },
  { tag: tags.definition(tags.variableName), color: '#f0e6d8' },
  { tag: tags.function(tags.variableName),   color: '#c4b0e8' },
  { tag: tags.function(tags.name),           color: '#c4b0e8' },
  { tag: tags.definition(tags.name),         color: '#c4b0e8' },
  { tag: tags.className,         color: '#89b8d4' },
  { tag: tags.typeName,          color: '#89b8d4' },
  { tag: tags.propertyName,      color: '#c4b0e8' },
  { tag: tags.attributeName,     color: '#c4b0e8' },
  { tag: tags.operator,          color: '#9e8e7a' },
  { tag: tags.punctuation,       color: '#6a5a4e' },
  { tag: tags.bracket,           color: '#8a7a6a' },
  { tag: tags.meta,              color: '#56493e' },
  { tag: tags.special(tags.variableName), color: '#e8a060' },
  { tag: tags.escape,            color: '#e8a060' },
])
